//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloSerie
    {
        public int IdArticuloSerie { get; set; }
        public int IdArticulo { get; set; }
        public int IdNota { get; set; }
        public int NroLote { get; set; }
        public string NumeroSerie { get; set; }
        public int Estado { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Nota Nota { get; set; }
    }
}
